# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.hcisolutions.ig.ch-emed-pmp
canonical: http://hcisolutions.ch/ig/ch-emed-pmp
name: CH_EMED_PMP
title: "CH EMED PMP (R4)"
description: FHIR implementation guide to show the use case PMP (plan de médication partagé) and the differences to the Swiss exchange format CH EMED.
status: draft
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2022-05-10
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2022+
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters -> Parameter: releaselabel
releaseLabel: CI Build 
publisher:
  name: HCI Solutions AG
contact:
  name: HCI Solutions AG
  telecom:
    system: url
    value: http://hcisolutions.ch

dependencies:
  ch.fhir.ig.ch-core: 2.0.0
  ch.fhir.ig.ch-emed: 2.0.0

pages:
  index.md:
    title: Home
  usecase-french.md:
    title: Scénarios d’utilisation (cas d’application)
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology

menu:
  Home: index.html
  Use Case: usecase-french.html
  Profiles: profiles.html
  Extensions: extensions.html
  Terminology: terminology.html
  Artifacts: artifacts.html

# Parameters
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
